apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "service.fullname" . }}
spec:
  selector:
    istio: {{ .Values.gateway.gatewayServiceName | default "ingressgateway" }}
  servers:
    {{- range $server := .Values.gateway.servers }}
    - port:
        number: {{ $server.port }}
        name: {{ $server.name }}
        protocol: {{ $server.protocol }}
      hosts:
        {{- range $host := $server.hosts }}
        - {{ $host }}
        {{- end }}
    {{- end }}
